import { Proposal } from './types';

export const MOCK_PROPOSALS: Proposal[] = [
  {
    id: '1',
    displayId: 'РП-2024-001',
    title: 'Внедрение модуля управления проектами в SAP S/4HANA для департамента капитального строительства',
    status: 'in_progress',
    initiator: 'Иванов А.С.',
    initiatorOrg: 'ООО «ТехКорп»',
    responsible: 'Смирнов В.И.',
    responsibleDept: 'Отдел ИТ',
    section: 'digital',
    system: 'SAP S/4HANA',
    gkNumber: 'ГК-2024/1',
    stage: 'Этап 2',
    priority: 'high',
    updatedAt: '22.04.2025',
    createdAt: '10.01.2024',
  },
  {
    id: '2',
    displayId: 'РП-2024-002',
    title: 'Оптимизация процесса согласования договоров в системе 1С:Документооборот',
    status: 'review',
    initiator: 'Петрова М.В.',
    initiatorOrg: 'АО «Газпром Нефть»',
    responsible: 'Морозова О.П.',
    responsibleDept: 'Отдел разработки',
    section: 'legal',
    system: '1С:Документооборот',
    gkNumber: 'ГК-2024/2',
    stage: 'Этап 1',
    priority: 'medium',
    updatedAt: '21.04.2025',
    createdAt: '15.02.2024',
  },
  {
    id: '3',
    displayId: 'РП-2024-003',
    title: 'Разработка интеграции между Битрикс24 и корпоративным порталом HR',
    status: 'new',
    initiator: 'Козлова Е.Н.',
    initiatorOrg: 'ООО «ИнфоСистемы»',
    responsible: 'Попов Л.Г.',
    responsibleDept: 'Инфраструктура',
    section: 'hr',
    system: 'Битрикс24',
    gkNumber: '—',
    stage: '—',
    priority: 'low',
    updatedAt: '20.04.2025',
    createdAt: '01.03.2024',
  },
  {
    id: '4',
    displayId: 'РП-2024-004',
    title: 'Обновление модуля HR в SAP HCM до версии 9.0 с переносом исторических данных',
    status: 'approved',
    initiator: 'Сидоров П.К.',
    initiatorOrg: 'ПАО «Сбербанк»',
    responsible: 'Лебедева Т.С.',
    responsibleDept: 'Безопасность',
    section: 'hr',
    system: 'SAP HCM',
    gkNumber: 'ГК-2024/1',
    stage: 'Этап 3',
    priority: 'high',
    updatedAt: '19.04.2025',
    createdAt: '05.03.2024',
  },
  {
    id: '5',
    displayId: 'РП-2024-005',
    title: 'Миграция данных из устаревшей системы учёта материалов на платформу MS Dynamics',
    status: 'rejected',
    initiator: 'Новиков Д.А.',
    initiatorOrg: 'АО «Ростелеком»',
    responsible: 'Смирнов В.И.',
    responsibleDept: 'Отдел ИТ',
    section: 'infra',
    system: 'MS Dynamics 365',
    gkNumber: 'ГК-2024/3',
    stage: 'Этап 1',
    priority: 'medium',
    updatedAt: '18.04.2025',
    createdAt: '10.03.2024',
  },
  {
    id: '6',
    displayId: 'РП-2024-006',
    title: 'Автоматизация отчётности по KPI для руководства и совета директоров',
    status: 'archived_completed',
    initiator: 'Иванов А.С.',
    initiatorOrg: 'ООО «ТехКорп»',
    responsible: 'Морозова О.П.',
    responsibleDept: 'Отдел разработки',
    section: 'digital',
    system: 'Power BI',
    gkNumber: 'ГК-2023/4',
    stage: 'Завершён',
    priority: 'medium',
    updatedAt: '15.12.2024',
    createdAt: '01.06.2023',
  },
  {
    id: '7',
    displayId: 'РП-2024-007',
    title: 'Внедрение системы двухфакторной аутентификации для всех корпоративных сервисов',
    status: 'archived_completed',
    initiator: 'Козлова Е.Н.',
    initiatorOrg: 'ООО «ИнфоСистемы»',
    responsible: 'Лебедева Т.С.',
    responsibleDept: 'Безопасность',
    section: 'security',
    system: 'Active Directory',
    gkNumber: 'ГК-2023/2',
    stage: 'Завершён',
    priority: 'critical',
    updatedAt: '30.11.2024',
    createdAt: '15.04.2023',
  },
  {
    id: '8',
    displayId: 'РП-2023-008',
    title: 'Интеграция CRM с системой ERP для автоматической синхронизации данных отдела продаж',
    status: 'archived_outdated',
    initiator: 'Новиков Д.А.',
    initiatorOrg: 'АО «Ростелеком»',
    responsible: 'Попов Л.Г.',
    responsibleDept: 'Инфраструктура',
    section: 'digital',
    system: 'Salesforce CRM',
    gkNumber: 'ГК-2022/1',
    stage: 'Отменён',
    priority: 'low',
    updatedAt: '10.06.2024',
    createdAt: '20.10.2022',
  },
  {
    id: '9',
    displayId: 'РП-2024-009',
    title: 'Разработка мобильного приложения для полевых сотрудников и инспекторов',
    status: 'review',
    initiator: 'Петрова М.В.',
    initiatorOrg: 'АО «Газпром Нефть»',
    responsible: 'Смирнов В.И.',
    responsibleDept: 'Отдел ИТ',
    section: 'digital',
    system: 'React Native',
    gkNumber: 'ГК-2024/2',
    stage: 'Этап 2',
    priority: 'high',
    updatedAt: '17.04.2025',
    createdAt: '12.04.2024',
  },
  {
    id: '10',
    displayId: 'РП-2024-010',
    title: 'Обновление инфраструктуры центра обработки данных: переход на гиперконвергентные решения',
    status: 'in_progress',
    initiator: 'Сидоров П.К.',
    initiatorOrg: 'ПАО «Сбербанк»',
    responsible: 'Попов Л.Г.',
    responsibleDept: 'Инфраструктура',
    section: 'infra',
    system: 'VMware vSAN',
    gkNumber: 'ГК-2024/3',
    stage: 'Этап 2',
    priority: 'critical',
    updatedAt: '23.04.2025',
    createdAt: '05.05.2024',
  },
  {
    id: '11',
    displayId: 'РП-2024-011',
    title: 'Внедрение электронного документооборота в юридическом отделе компании',
    status: 'new',
    initiator: 'Иванов А.С.',
    initiatorOrg: 'ООО «ТехКорп»',
    responsible: 'Лебедева Т.С.',
    responsibleDept: 'Безопасность',
    section: 'legal',
    system: 'ДЕЛО (ЭОС)',
    gkNumber: '—',
    stage: '—',
    priority: 'medium',
    updatedAt: '16.04.2025',
    createdAt: '01.07.2024',
  },
  {
    id: '12',
    displayId: 'РП-2024-012',
    title: 'Разработка аналитического дашборда для мониторинга KPI инфраструктурных проектов',
    status: 'approved',
    initiator: 'Козлова Е.Н.',
    initiatorOrg: 'ООО «ИнфоСистемы»',
    responsible: 'Морозова О.П.',
    responsibleDept: 'Отдел разработки',
    section: 'digital',
    system: 'Grafana + Prometheus',
    gkNumber: 'ГК-2024/1',
    stage: 'Этап 1',
    priority: 'high',
    updatedAt: '14.04.2025',
    createdAt: '20.07.2024',
  },
  {
    id: '13',
    displayId: 'РП-2024-013',
    title: 'Оптимизация и реиндексация базы данных Oracle для повышения производительности на 40%',
    status: 'in_progress',
    initiator: 'Новиков Д.А.',
    initiatorOrg: 'АО «Ростелеком»',
    responsible: 'Смирнов В.И.',
    responsibleDept: 'Отдел ИТ',
    section: 'infra',
    system: 'Oracle DB',
    gkNumber: 'ГК-2024/2',
    stage: 'Этап 3',
    priority: 'high',
    updatedAt: '12.04.2025',
    createdAt: '15.08.2024',
  },
  {
    id: '14',
    displayId: 'РП-2023-014',
    title: 'Внедрение системы управления знаниями на базе Confluence для технических команд',
    status: 'archived_outdated',
    initiator: 'Петрова М.В.',
    initiatorOrg: 'АО «Газпром Нефть»',
    responsible: 'Попов Л.Г.',
    responsibleDept: 'Инфраструктура',
    section: 'hr',
    system: 'Confluence',
    gkNumber: 'ГК-2022/3',
    stage: 'Отменён',
    priority: 'medium',
    updatedAt: '05.03.2024',
    createdAt: '10.09.2022',
  },
  {
    id: '15',
    displayId: 'РП-2024-015',
    title: 'Разработка API для интеграции корпоративных систем с государственными сервисами СМЭВ',
    status: 'review',
    initiator: 'Сидоров П.К.',
    initiatorOrg: 'ПАО «Сбербанк»',
    responsible: 'Лебедева Т.С.',
    responsibleDept: 'Безопасность',
    section: 'security',
    system: 'СМЭВ 3.0',
    gkNumber: 'ГК-2024/3',
    stage: 'Этап 1',
    priority: 'critical',
    updatedAt: '22.04.2025',
    createdAt: '01.09.2024',
  },
  {
    id: '16',
    displayId: 'РП-2024-016',
    title: 'Автоматизация закупочных процессов и тендерных процедур в системе SAP Ariba',
    status: 'new',
    initiator: 'Иванов А.С.',
    initiatorOrg: 'ООО «ТехКорп»',
    responsible: 'Морозова О.П.',
    responsibleDept: 'Отдел разработки',
    section: 'finance',
    system: 'SAP Ariba',
    gkNumber: '—',
    stage: '—',
    priority: 'high',
    updatedAt: '11.04.2025',
    createdAt: '10.10.2024',
  },
  {
    id: '17',
    displayId: 'РП-2024-017',
    title: 'Миграция корпоративной почты на Microsoft Exchange Online и внедрение Teams',
    status: 'approved',
    initiator: 'Козлова Е.Н.',
    initiatorOrg: 'ООО «ИнфоСистемы»',
    responsible: 'Смирнов В.И.',
    responsibleDept: 'Отдел ИТ',
    section: 'infra',
    system: 'Microsoft 365',
    gkNumber: 'ГК-2024/1',
    stage: 'Этап 2',
    priority: 'medium',
    updatedAt: '09.04.2025',
    createdAt: '20.10.2024',
  },
  {
    id: '18',
    displayId: 'РП-2024-018',
    title: 'Внедрение SIEM-системы для мониторинга инцидентов информационной безопасности',
    status: 'rejected',
    initiator: 'Новиков Д.А.',
    initiatorOrg: 'АО «Ростелеком»',
    responsible: 'Лебедева Т.С.',
    responsibleDept: 'Безопасность',
    section: 'security',
    system: 'MaxPatrol SIEM',
    gkNumber: 'ГК-2024/3',
    stage: 'Этап 1',
    priority: 'critical',
    updatedAt: '08.04.2025',
    createdAt: '01.11.2024',
  },
];

export const STATUS_OPTIONS = [
  { value: '', label: 'Все статусы' },
  { value: 'new', label: 'Новое' },
  { value: 'review', label: 'На рассмотрении' },
  { value: 'in_progress', label: 'В работе' },
  { value: 'approved', label: 'Согласовано' },
  { value: 'rejected', label: 'Отклонено' },
  { value: 'archived_completed', label: 'Завершено' },
  { value: 'archived_outdated', label: 'Устарело' },
];

export const SECTION_OPTIONS = [
  { value: '', label: 'Все разделы' },
  { value: 'digital', label: 'Цифровизация' },
  { value: 'infra', label: 'Инфраструктура' },
  { value: 'security', label: 'Информационная безопасность' },
  { value: 'hr', label: 'HR и кадры' },
  { value: 'finance', label: 'Финансы' },
  { value: 'legal', label: 'Юридический' },
];

export const SYSTEM_OPTIONS = [
  { value: '', label: 'Все системы' },
  { value: 'SAP S/4HANA', label: 'SAP S/4HANA' },
  { value: '1С:Документооборот', label: '1С:Документооборот' },
  { value: 'Битрикс24', label: 'Битрикс24' },
  { value: 'MS Dynamics 365', label: 'MS Dynamics 365' },
  { value: 'Oracle DB', label: 'Oracle DB' },
  { value: 'Confluence', label: 'Confluence' },
  { value: 'Microsoft 365', label: 'Microsoft 365' },
];

export const PRIORITY_OPTIONS = [
  { value: '', label: 'Все приоритеты' },
  { value: 'critical', label: 'Критический' },
  { value: 'high', label: 'Высокий' },
  { value: 'medium', label: 'Средний' },
  { value: 'low', label: 'Низкий' },
];
